# Change these first
owner: factiverse # Your GitHub organization or username, where this repository lives
repo: api-upptime # The name of this repository

sites:
  - name: GET to /dummy
    url: https://api.factiverse.no/v1/dummy
    maxResponseTime: 1500

workflowSchedule:
  graphs: "*/60 * * * *"
  responseTime: "*/60 * * * *"
  staticSite: "0 0 * * *"
  summary: "*/60 * * * *"
  updateTemplate: "*/60 * * * *"
  updates: "*/60 * * * *"
  uptime: "*/60 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /api-upptime
  logoUrl: https://raw.githubusercontent.com/factiverse/api-upptime/master/assets/Factiverse%20Logo.png
  name: Factiverse Systems Status
  introTitle: "**Factiverse** Systems Status**"
  introMessage: This site monitors if our systems are up and running as intended.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
