# Change these first
owner: factiverse # Your GitHub organization or username, where this repository lives
repo: upptime-prod # The name of this repository

sites:
  - name: /statistics/claim_search
    url: https://prod.factiverse.ai/v1/statistics/claim_search
    method: GET
    headers:
      - "Authorization: Bearer $API_TOKEN"
      - "accept: application/json"
      - "Content-Type: application/json"
    assignees:
      - tobiastykvart

workflowSchedule:
  graphs: "*/10 * * * *"
  responseTime: "*/10 * * * *"
  staticSite: "*/10 * * * *"
  summary: "*/10 * * * *"
  updateTemplate: "*/10 * * * *"
  updates: "*/10 * * * *"
  uptime: "*/10 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime-prod
  logoUrl: https://raw.githubusercontent.com/factiverse/api-upptime/master/assets/Factiverse%20Logo.png
  name: Factiverse Systems Status
  introTitle: "**Factiverse** Systems Status**"
  introMessage: This site monitors if our systems are up and running as intended.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
